"""Migration altering the transaction_type field in Trans model."""

# Generated by Django 4.2.25 on 2025-12-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    """Database migration altering transaction_type field length."""

    dependencies = [
        ("finance", "0002_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trans",
            name="transaction_type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")],
                max_length=10,
            ),
        ),
    ]
    